Don't use "bitmap" property of TileGrid objects
In 8.0, the TIleGrid adds its own "bitmap" property. This interfered, causing the exception reported in guide feedback:
```
Traceback (most recent call last):
File "code.py", line 59, in
File "code.py", line 40, in __init__
NotImplementedError: Call super().__init__() before accessing native object.
```