Make the Twitter_API example work
(1) on the import section, I prefer to use adafruit_binascii library than a version specific to this example
(2) apparently requests is not outside of esp32spi
(3) the code to compute or ask Twitter the bearer_token fail for me ... but when I created my Twitter Developper account, in addition to the 'twitter_api_key' and 'twitter_secret_key', there was a bearer token that I have put in my secrets.py file :

'twitter_bearer_token' : 'verylongstring'

The guide should be updated to take that into account I guess.

I have not deleted the function get_bearer_token(), but it is not in use anymore.

Here is the error I get (I did not try to fix, but I had it multiple time).

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "main_twitter.py", line 77, in <module>
  File "main_twitter.py", line 47, in get_bearer_token
  File "adafruit_requests.py", line 296, in post
  File "adafruit_requests.py", line 251, in request
  File "adafruit_requests.py", line 235, in request
  File "adafruit_esp32spi/adafruit_esp32spi_socket.py", line 102, in readline
RuntimeError: Didn't receive full response, failing out